version: "3"
services:
  indexer:
    image: node:21-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: tx.js
  server:
    image: hackbg/undexer-lighttpd
    build:
      context: ./docker
      dockerfile: lighttpd.Dockerfile
    volumes:
      - ./data:/data:ro
      - ./lighttpd.conf:/lighttpd.conf:ro
    command: lighttpd -D -f /lighttpd.conf
    ports:
      - 8080
