version: "3"
services:
  indexer:
    image: node:21-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: --import @ganesha/esbuild-wasm index.js
  server:
    image: hackbg/undexer-lighttpd
    build:
      context: ./docker
      dockerfile: lighttpd.Dockerfile
    volumes:
      - ./data:/data:ro
      - ./lighttpd.conf:/lighttpd.conf:ro
    command: lighttpd -D -f /lighttpd.conf
    ports:
      - 8080
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=insecure
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
